* One or two levels in QFeatures (closed)
:PROPERTIES:
:CUSTOM_ID: one-or-two-levels-in-qfeatures-closed
:END:
One or two assay levels could be considered in QFeatures:

- one level: each SE contains only a single assay, and when an SE is
  processed (log-transformed, normalised, ...) in a way that its
  dimensions stay the same, a new SE is created and added to the
  QFeatures object.

- two level: SEs can contain multiple assays, and when an SE is
  processed (log-transformed, normalised, ...) in a way that its
  dimensions stay the same, a new assay is added to that SE.

This [[https://stat.ethz.ch/pipermail/bioc-devel/2020-January/016096.html][question]] on the bioc-devel list ask for advice on SE processing,
and whether a new SE or new assay in the original SE should be
preferred. While the letter is arguably more elegant, and is also used
in SingleAssayExperiment pipelines, it doesn't seem to be the case
when using SummarizedExperiments.

As for features (or [[https://github.com/waldronlab/MultiAssayExperiment/issues/266][MultiAssayExperiments in general]]), the two-level
approach isn't readily available out-of-the-box, and would require
additional developments:

- Every function that operates on an SE of a QFeatures object would need
  to allow the user to specify which assay to use (and/or by default use
  the latest one).

- The =show,QFeatures= method would need to display the number/names of
  the assays in each SE to make these two levels explicit.

Despite the elegant of the two-level option, it seems that the
additional development isn't warranted at this time.

The [[https://github.com/rformassspectrometry/QFeatures/issues/37][=updateAssay= function]] was originally intended for the two-level
approach, i.e. to add an assay to an SE. This is not considered
anymore (for now, at least).

There is one exception though. When aggregating features with
=aggregateFeatures()=, a second assay is added, named =aggcounts= that
counts the number of features that were aggregate for each sample and
each low-level features.

* How to add new assays (closed)
:PROPERTIES:
:CUSTOM_ID: how-to-add-new-assays-closed
:END:
1. Through aggregation with =aggregateFeatures=.

2. Processing an SE.

This can/could be done explicitly with =addAssay=

#+begin_example
addAssay(cptac, logTransform(cptac[["peptides"]]), name = "peptides_log")
addAssay(cptac, logTransform(cptac[[1]]), name = "peptides_log")
#+end_example

or implicitly

#+begin_example
logTransform(cptac, "peptides", name = "peptides_log")
logTransform(cptac, 1, name = "peptides_log")
#+end_example

3. [@3] Joining SEs (for example multiple TMT batches) (TODO)

#+begin_example
joinAssays(QFeatures, c("pep_batch1", "pep_batch2", "pep_batch3"), name = "peptides")
joinAssays(QFeatures, c(1, 2, 3), name = "peptides")
#+end_example

See below.

* QFeatures API
:PROPERTIES:
:CUSTOM_ID: qfeatures-api
:END:
*** Processing functions
:PROPERTIES:
:CUSTOM_ID: processing-functions
:END:
- A processing function that acts on a Feature's assay (typically a
  =SummarizedExperiment= or a =SingleCellExperiment=) such as
  =process(object)=, returns a new object of the same type.

- A processing function such =process(object, i)=, that acts on a
  Feautre object takes a second argument =i=, that can be a vector of
  indices or names, returns a new object of class QFeatures with its
  assay(s) =i= modified according to =process(object[[i]])=.

- The argument =i= mustn't be missing, i.e. one shouldn't (at least in
  general) permit to (blindly) apply some processing on all assays.

*** Assays
:PROPERTIES:
:CUSTOM_ID: assays
:END:
- Assays should have unique rownames (even though this isn't required
  for SEs). If they aren't, only the first occurence of the name is
  kept:

#+begin_example
hlpsms <- hlpsms[1:5000, ] ## faster

ft1 <- readQFeatures(hlpsms, ecol = 1:10, name = "psms", fname = "Sequence")
sum(rownames(ft1[[1]]) == "ANLPQSFQVDTSk")
ft1 <- aggregateFeatures(ft1, "psms", fcol = "Sequence",
                         name = "peptides", fun = colSums)
sapply(rownames(ft1), anyDuplicated)
ft1

## subsetting still works
ft2 <- subsetByFeature(ft1, "ANLPQSFQVDTSk")
ft2
#+end_example

The underlying reason why this fails is due to matrix subsetting by name
when these names aren't unique.

#+begin_src R
m <- matrix(1:10, ncol = 2)
colnames(m) <- LETTERS[1:2]
rownames(m) <- c("a", letters[1:4])
m
m["a", ]
#+end_src

And of course, this affects SEs ...

#+begin_src R
se <- SummarizedExperiment(m)
assay(se["a", ])
#+end_src

... and MultiAssayExperiments.

Note that in the example above, ="ANLPQSFQVDTSk"= is present in both the
=psms= and =peptides= assays, and the

#+begin_example
for (k in setdiff(all_assays_names, leaf_assay_name)) { ... }
#+end_example

loop in =.subsetByFeature= isn't executed at all. This will need to be
investigated. But the behaviour above can be reproduced even when that's
not the case. See

#+begin_example
hlpsms$Sequence2 <- paste0(hlpsms$Sequence, "2")
ft1 <- readQFeatures(hlpsms, ecol = 1:10, name = "psms", fname = "Sequence2")
...
#+end_example

This could be *fixed* by switching to indices:

#+begin_example
> (i <- which(rownames(m) == "a"))
[1] 1 2
> m[i, ]
  A B
a 1 6
a 2 7
> se[i, ]
class: SummarizedExperiment
dim: 2 2
metadata(0):
assays(1): ''
rownames(2): a a
rowData names(0):
colnames(2): A B
colData names(0):
#+end_example

See issue #91.

* Assay links
:PROPERTIES:
:CUSTOM_ID: assay-links
:END:
Currently, we have

- Assay links produces by =aggregateFeatures= and manually with
  =addAssayLink=.

- /One-to-one/ Assay links produced by a processing function such as
  =logTransform= or with =addAssayLinkOneToOne=. These contain
  ="OneToOne"= in the =fcol= slot (issue 42).

- There will be a need for an assay link stemming from combining assays
  (see below and issue 52).

* Joining assays (closed)
:PROPERTIES:
:CUSTOM_ID: joining-assays-closed
:END:
To /combine/ assays, we also need 1. relaxed =MatchedAssayExperiment=
constrains (see #46) 2. assay links with multiple parent assays (see
#52)

=combine,MSnSet,MSnSet= does two things, i.e. =rbind= and =cbind=. Here,
we nedd (at least in a first instance) and have
=cbind,SummarizedExperiment=.

- do we need some constrains requiering identical rownames?
  =cbind,SummarizedExperiment= uses the mcols to check whether rows
  match.
- should unique rows in one assay get NAs in the other one? yes!

We need a *join*-type of function, that adds NAs at the assay level. To
do this, we need to have a union of features before rbinding the assays.

As for rowData, we want to

- keep the mcols that match exactly between assays (ex: PeptideSequence,
  ProteinAccession, ...)
- remove mcols that differ between assays (ex: PEP, qvalues, charge,
  rtime, ...)

The row data will be accessible through links between assays anyway.

Naming:

#+begin_example
joinAssays(QFeatures, c("pep_batch1", "pep_batch2", "pep_batch3"), name = "peptides")
joinAssays(QFeatures, c(1, 2, 3), name = "peptides")
#+end_example

Algorithm: 1. Find which mcols to keep 2. Extend with rownames and NAs
(depending on type of join) 3. Order assays 4. cbind assays (see
=cbind,SummarizedExperiment=)

Do we want a public /join/ for SummarizedExperiments? Discuss with SE
maintainers.

Note: if we were to have assay from multiple fractions to be /rbind/ed,
we could consider a =rbindAssays=, =mergeFractions=, =bindFractions=,
...

* Replacing vs adding assays
:PROPERTIES:
:CUSTOM_ID: replacing-vs-adding-assays
:END:
Issues
[[file:193][https://github.com/rformassspectrometry/QFeatures/issues/193]]
and
[[file:186][https://github.com/rformassspectrometry/QFeatures/issues/186]].

Currently, assays are replaced with - filterNA() - filterFeatures() (and
possibly others)

Sometimes, we want to add, rather than replace, for example if we want
to test/assess the effect of different filters. This could be defined by
the =names= argument. If missing (default), the assays are replaced. If
present and of same length than =i=, new assays are added.

- When it comes to data processing, we could also have a /subset/
  argument, that would implicitly only process a subset of rows so as to
  avoid to explicitly store the subset/intermediate assay.

- A more radical change would be for =filterFeatures()= to add a rowData
  logical that defines the rows to be filtered.

There are multiple ideas/discussion replated to QFeatures becoming very
large (and slow). Rather than adding more assays, we could: - use
logical for subsetting; - use multiple assays within a
SingleCellExperiment (or SE), when the dimensions remain identical (for
exmple logTransform()); - have a unique database to handle and manage
all data (assays and rowData).

But we agree that the interface, for the user, should remain simple,
i.e. different assays. For now, keep the same philosophy and create new
assays for all operations, and start a reflexion for more in-depth
refactoring.

See also [[https://github.com/rformassspectrometry/QFeatures/issues/171][HDF5 backend issue]].

* Devel roadmap
:PROPERTIES:
:CUSTOM_ID: devel-roadmap
:END:
** scp
:PROPERTIES:
:CUSTOM_ID: scp
:END:
- scp data [[https://github.com/UCLouvain-CBIO/scp/issues/48][import]]
  documentation. Current approach doesn't work well for LFQ. Add
  documentation, and align scpGUIImport.
- [[https://github.com/UCLouvain-CBIO/scp/issues/44][Compute mertics per cell]] is clumsy/ad hoc at the moment. We need a
  general function to iterates over cells/features and store
  automatically in col/rowData.  What is computed defined by a
  user-defined function. For example =*OverSample()= and
  =*OverFeatures()= and a more general =computeMetric()=. These would
  added to =QFeatures= with specialised metrics implemented in =scp=.
- Merge scplainer into scp (issue [[https://github.com/UCLouvain-CBIO/scp/pull/45][45]]): needs unit tests
- [[https://github.com/UCLouvain-CBIO/scp/issues/40][Missing data vignette/report]]: unit tests coming soon
- [[https://github.com/UCLouvain-CBIO/scp/issues/42][readScpFromDIANN()]] needs unit test and some refactoring
- [[https://github.com/UCLouvain-CBIO/scp/issues/34][=divideByReference()=]] is a batch correction method, and should be
  moved to QFeatures, and made accessible as part of a more general
  =batchCorrect()= interface, that can also be used for combat and
  limma.

** scpdata
:PROPERTIES:
:CUSTOM_ID: scpdata
:END:
- Keep [[https://github.com/UCLouvain-CBIO/scpdata/issues/15][adding new
  datasets]].

** QFeatures
:PROPERTIES:
:CUSTOM_ID: qfeatures
:END:
- [[https://github.com/rformassspectrometry/QFeatures/issues/193][All QFeatures functions should add assays]] - see 'Replacing vs adding
  assays' above.
- =filterNA()= on columns (see
  [[file:173][https://github.com/rformassspectrometry/QFeatures/issues/173]]].  Or
  should we use =computeMetricOverCells()= with metric =nNA=?
- Small bugs: [[https://github.com/rformassspectrometry/QFeatures/issues/174][nNA() on empty assays]] and [[https://github.com/rformassspectrometry/QFeatures/issues/196][longFormat(se, rowvars)]]
  (eventhough the latter should probbaly use tidy versions).
- Interest in [[https://github.com/rformassspectrometry/QFeatures/issues/188][pseudo-bulking]], which should work out-of-the-box, since
  the colData is unique for all assaya (Chris to address during
  post-doc).

* Tabular input (issue 199)
:PROPERTIES:
:CUSTOM_ID: tabular-input-issue-199
:END:
1. Single-set case, multiplexed: requires =colAnnotation= only. Also
   LF with a re-ordered peptide/protein-level table (runs are missing
   in this case).

#+begin_example
|------+------------+-----------|
| cols | Quant 1..N | more cols |
|      |            |           |
|      |            |           |
|      |            |           |
|------+------------+-----------|
#+end_example

#+begin_example
readQFeatures(hlpsms, quantCols = 1:10)
readQFeatures(hlpsms, colAnnotation = colann)

## also possible, but redundant
readQFeatures(hlpsms, colAnnotation = colann, quantCols = 1:10)
#+end_example

2. Multi-set case, multiplexed: requires =colAnnotation= and =runCol=.

#+begin_example
|-----+------+------------+-----------|
| Run | cols | Quant 1..N | more cols |
|   1 |      |            |           |
|   1 |      |            |           |
|-----+------+------------+-----------|
|   2 |      |            |           |
|-----+------+------------+-----------|
#+end_example

#+begin_example
readQFeatures(hlpsms, quantCols = 1:10, runCol = "file")
readQFeatures(hlpsms, colAnnotation = colann, runCol = "file")
#+end_example

3. Multi-set case, LF: requires =colData= and =runCol= with a optional
   =multiplexing= (for plexDIA).

#+begin_example
|-----+------+---------+-----------+-----------|
| Run | cols | Quant 1 | more cols | multiplex |
|   1 |      |         |           |           |
|   1 |      |         |           |           |
|-----+------+---------+-----------+-----------|
|   2 |      |         |           |           |
|-----+------+---------+-----------+-----------|
#+end_example

4. Special case DIANN. A specialised function that parses the table to
   case 2.

Users can either use the arguments above or a =colAnnotation= data.frame
(that will become the =colData=).

** DIANN data
:PROPERTIES:
:CUSTOM_ID: diann-data
:END:
- DIANN data is in long format
- readQFeaturesFromDIANN() would need to transform from long to wide,
  then use readQFeatures()
- multiplexing: NULL or "none"

#+begin_example
dfr |>
  diannWider() |>
  readQFeatures()

readQFeaturesFromDIANN <- funtion(dfr, multiplexing = NULL, ...) {
    if (!is.null(multiplexing))
        x <- .diannWider(multiplexing)
    readQFeatures(x, ...)
}
#+end_example

* Possible optimsations
:PROPERTIES:
:CUSTOM_ID: possible-optimsations
:END:
Simple ones

- In =longForm()= have a =na.rm= argument and propagate it to
  =reshape2::melt()= for each assay. This would require to loop over
  assay, extract them with =getWithColData()=, and use our own
  =longFormSE()= supporting =na.rm=.
- Parallelise =aggregateFeatures()=, =logTransform()=,
  =scaleTransform()=, =impute()=, ...
